# Site settings
title: hackrush
email: some-email@some-mail.com
description: This is just the initial template. This site is a WIP and will be completed soon.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https:hackrush01.github.io" # the base hostname & protocol for your site
author: hackrush
street_address: Street
city: City
state: State
zip_code: 99994447
country: Country
phone: 11452145987

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# Social settings
facebook_url: https://www.facebook.com/
github_url: https://github.com/hackrush01

# Build settings
markdown: kramdown

sass:
  style: compressed
